version: '3.8'

services:
  calibre:
    build: .
    ports:
      - "${CALIBRE_PORT:-8080}:8080"
    volumes:
      - "${CALIBRE_LIBRARY_PATH:-./library}:/home/calibre/library"
    environment:
      - CALIBRE_PORT=8080
      - CALIBRE_LIBRARY_PATH=/home/calibre/library
